#!/usr/bin/bash
choice=$1
if [[ $# -eq 1 ]]; then
	if [ $1 == "-h" ]; then
		echo "Cara penggunaan:

• ydl <link video youtube> = Untuk melihat daftar kualitas
  Contoh:
	ydl https://youtu.be/dmSmSuqb9RI

• ydl <kode kualitas> <link video youtube> = Untuk mendownload video dalam kualitas tertentu
  Contoh:
	ydl 720p https://youtu.be/dmSmSuqb9RI 

  Daftar kualitas yang didukung:
	- 144p, 144p60HDR, 144pHDR
	- 240p, 240p60HDR, 240pHDR
	- 360p, 360p60HDR, 360pHDR
	- 480p, 480p60HDR, 480pHDR
	- 720p, 720p60, 720p60HDR
	- 1080p, 1080p60, 1080p60HDR
	- 1440p, 1440p60, 1440p60HDR
	- 4K, 4K60, 4K60HDR

• ydl <kode kualitas> <format video> <link video youtube> - Untuk mendownload video dalam format tertentu
  Contoh:
	ydl 1080p60 mkv https://youtu.be/dmSmSuqb9RI 

  Format video yang didukung:
	- mp4
	- mkv"		
	else
		youtube-dl -F $1
	fi
elif [[ $# -eq 2 ]]; then
	case $choice in
		'144p')
			quality=160
			;;  
		'144p60HDR')
			quality=694
			;;
		'144pHDR')
			quality=394
			;;
		'240p')
			quality=133
			;;
		'240p60HDR')
			quality=695
			;;
		'240pHDR')
			quality=395
			;;
		'360p')
			quality=134
			;;
		'360p60HDR')
			quality=696
			;;
		'360pHDR')
			quality=396
			;;
		'480p')
			quality=135
			;;
		'480p60HDR')
			quality=697
			;;
		'480pHDR')
			quality=397
			;;
		'720p')
			quality=136 
			;;
		'720p60HDR')
			quality=698
			;;
		'720p60')
			quality=298
			;;
		'1080p')
			quality=137
			;;
		'1080p60')
			quality=299
			;;
		'1080p60HDR')
			quality=699
			;;
		'1440p')
			quality=264
			;;
		'1440p60')
			quality=304
			;;
		'1440p60HDR')
			quality=700
			;;
		'4K')
			quality=266
			;;
		'4K60')
			quality=305
			;;
		'4K60HDR')
			quality=701
			;;
	esac
	title=$(youtube-dl $2 -se)
	echo "Title: $title"
	if youtube-dl -f ${quality}+140 $2 -c -o '%(title)s'; then
		echo "Download Success!"
		youtube-dl --rm-cache-dir
	else
		echo "Download Failed!"
	fi
elif [[ $# -eq 3 ]]; then
	if [[ $2 == "mp4" ]]; then
		case $choice in
			'144p')
				quality=160
				;;  
			'144p60HDR')
				quality=694
				;;
			'144pHDR')
				quality=394
				;;
			'240p')
				quality=133
				;;
			'240p60HDR')
				quality=695
				;;
			'240pHDR')
				quality=395
				;;
			'360p')
				quality=134
				;;
			'360p60HDR')
				quality=696
				;;
			'360pHDR')
				quality=396
				;;
			'480p')
				quality=135
				;;
			'480p60HDR')
				quality=697
				;;
			'480pHDR')
				quality=397
				;;
			'720p')
				quality=136 
				;;
			'720p60HDR')
				quality=698
				;;
			'720p60')
				quality=298
				;;
			'1080p')
				quality=137
				;;
			'1080p60')
				quality=299
				;;
			'1080p60HDR')
				quality=699
				;;
			'1440p')
				quality=264
				;;
			'1440p60')
				quality=304
				;;
			'1440p60HDR')
				quality=700
				;;
			'4K')
				quality=266
				;;
			'4K60')
				quality=305
				;;
			'4K60HDR')
				quality=701
				;;
		esac
		if youtube-dl -f ${quality}+140 $3 -c -o '%(title)s'; then
			echo "Download Success!"
			youtube-dl --rm-cache-dir
		else
			echo "Download Failed!"
		fi
	elif [[ $2 == "mkv" ]]; then
		case $choice in
			'144p')
				quality=278
				;;  
			'144p60HDR')
				quality=694
				;;
			'144pHDR')
				quality=394
				;;
			'240p')
				quality=242
				;;
			'240p60HDR')
				quality=695
				;;
			'240pHDR')
				quality=395
				;;
			'360p')
				quality=243
				;;
			'360p60HDR')
				quality=696
				;;
			'360pHDR')
				quality=396
				;;
			'480p')
				quality=244
				;;
			'480p60HDR')
				quality=697
				;;
			'480pHDR')
				quality=397
				;;
			'720p')
				quality=247 
				;;
			'720p60HDR')
				quality=698
				;;
			'720p60')
				quality=302
				;;
			'1080p')
				quality=248
				;;
			'1080p60')
				quality=303
				;;
			'1080p60HDR')
				quality=699
				;;
			'1440p')
				quality=271
				;;
			'1440p60')
				quality=308
				;;
			'1440p60HDR')
				quality=700
				;;
			'4K')
				quality=313
				;;
			'4K60')
				quality=315
				;;
			'4K60HDR')
				quality=701
				;;
		esac
		if youtube-dl -f ${quality}+140 $3 -c -o '%(title)s'; then
			echo "Download Success!"
			youtube-dl --rm-cache-dir
		else
			echo "Download Failed!"
		fi
	fi
else
	echo "Command tidak valid!"
fi
